### ISSUE TITLE
Contacto tiene que ser una URL?, Tampoco no informa de errores de logeo

### ISSUE THREAD

**Issue by fabriziotonin** [RollingTeam/ProyectoCurson#48]
Al crear un Curso nuevo no me avisa si estoy logeado, el input de contacto deberia ser URL o email

![image](https://user-images.githubusercontent.com/51201108/108611792-ddfa1000-73c0-11eb-9373-0dced9445496.png)

**Comment by florpistan** [comment]
- [x] input contacto type url
si no estás logueado, en vez de aparecer el botón "publicar curso" te aparece un botón de login para que te loguees @fabriziotonin
