### ISSUE TITLE
Notificar al usuario y Eliminar datos sensibles

### ISSUE THREAD

**Issue by fabriziotonin** [RollingTeam/ProyectoCurson#50]
Al crear un Curso se deberia notificar al usuario de si a sido exitoso o no.
Eliminar la data sensible de los console log

![image](https://user-images.githubusercontent.com/51201108/108611885-d0915580-73c1-11eb-82a2-3f303cdc8d9c.png)

**Comment by florpistan** [comment]
- [x] eliminar console.log
- [ ] agregar alert informando si la solicitud del curso se envió o no
